application: songz-rmwad2
version: v1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /api(/.*)?
  script: api.py

- url: /.*
  script: main.py
